### ISSUE TITLE
Write a wrapper of the `models` namespace

### ISSUE THREAD

**Issue by gvegayon** [UofUEpi/epiworldR#2]
The epiworld C++ library has many predefined models. These should be included directly via R wrappers. The list of models to add is:

- [x] sis
- [x] sir
- [x] seir
- [x] sirconnected
- [x] seirconnected

This list will grow, eventually. I'll start with the first one.

**Comment by gvegayon** [comment]
@derekmeyer37, I was able to build a wrapper for a SIR model. There are other four models [here](https://github.com/UofUEpi/epiworld/tree/master/include/epiworld/models). The next step will be to:

1. Copy the src/model_sir.cpp file, one for each model.
2. Document the functions using roxygen2 (so we need to create R wrappers)

**Comment by gvegayon** [comment]
Hey @derekmeyer37, here is a good reference about [S3 methods and classes](https://adv-r.hadley.nz/s3.html).

**Comment by derekmeyer37** [comment]
Thanks! The walkthrough of creating wrappers was very helpful. Have a great weekend!

**Comment by gvegayon** [comment]
Great! I'm glad you think it was useful.

Enjoy the weekend!

George G. Vega Yon, Ph.D.
https://ggvy.cl
Pronouns
<https://www.aclunc.org/article/frequently-asked-questions-whats-pronoun>:
he/him/él
